# Generated by Django 3.1.2 on 2020-11-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('featured', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='FeaturedPost',
        ),
    ]
