# Generated by Django 3.2.11 on 2022-02-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=255, unique=True, verbose_name='Name'), max_length=200, unique=True),
        ),
    ]
