# Generated by Django 3.2.11 on 2022-03-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0002_quiz_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(default='test', max_length=200, unique=True),
        ),
    ]
