# Generated by Django 3.1.2 on 2020-12-08 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('subTitle', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='quiz/%Y/%m/%d/')),
                ('option1', models.CharField(max_length=50, unique=True)),
                ('option2', models.CharField(max_length=50, unique=True)),
                ('option3', models.CharField(max_length=50, unique=True)),
                ('option4', models.CharField(max_length=50, unique=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quiz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
