# Generated by Django 3.1.2 on 2021-01-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiztakers',
            options={'verbose_name': 'QuizTaker', 'verbose_name_plural': 'QuizTakers'},
        ),
    ]
