# Generated by Django 3.1.2 on 2021-01-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210119_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
