# Generated by Django 3.1.2 on 2020-12-08 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20201208_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='progress',
        ),
    ]
