# Generated by Django 3.1.2 on 2021-01-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210119_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='questions_count',
            field=models.IntegerField(default=10),
        ),
    ]
