# Generated by Django 3.1.2 on 2020-12-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20201208_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='quiz/%Y/%m/%d/'),
        ),
    ]
