# Generated by Django 3.1.2 on 2021-01-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20210103_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description_text',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
