# Generated by Django 3.1.2 on 2021-01-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20210106_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description_text',
            field=models.TextField(max_length=250, unique=True),
        ),
    ]
