# Generated by Django 3.1.2 on 2021-02-01 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20210201_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='response_1',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='response_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.choice'),
        ),
    ]
