# Generated by Django 3.1.2 on 2021-02-05 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20210201_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='response_option',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='response_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='response_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.question', verbose_name='Question'),
        ),
    ]
