# Generated by Django 3.1.2 on 2021-01-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_choice_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='QuizAnswer',
        ),
    ]
