# Generated by Django 3.1.2 on 2021-01-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20210110_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['pub_date'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
