# Generated by Django 3.1.2 on 2021-02-05 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_remove_userresponse_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='quiztaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiztakers'),
        ),
    ]
