# Generated by Django 3.1.2 on 2021-02-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20210209_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='response_3',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
