# Generated by Django 3.1.2 on 2021-02-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_auto_20210209_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='quiz',
        ),
    ]
