# Generated by Django 3.1.7 on 2021-02-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_auto_20210226_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='response_1',
            field=models.IntegerField(null=True),
        ),
    ]
