# Generated by Django 3.1.7 on 2021-02-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_auto_20210227_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='response_1',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
