# Generated by Django 3.1.7 on 2021-03-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterField(
            model_name='application',
            name='app_type',
            field=models.CharField(choices=[('LI', 'Low Intensity'), ('MI', 'Med Intensity'), ('HI', 'High Intensity')], default='MI', max_length=2, verbose_name='Resource Intensive'),
        ),
        migrations.AlterField(
            model_name='application',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='apps/%Y/%m/%d/', verbose_name='Logo (1024x1024)'),
        ),
    ]
