# Generated by Django 3.1.2 on 2021-02-05 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('choices', models.ManyToManyField(null=True, to='questionary.Choice')),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_1', models.CharField(choices=[('1', '250-300'), ('2', '300-500'), ('3', '500-750'), ('4', '1000-1500'), ('5', '1500+')], max_length=20)),
                ('response_2', models.CharField(choices=[('1', 'Work'), ('2', 'School'), ('3', 'Leisure/Hobby'), ('4', 'Everything')], max_length=20)),
                ('response_3', models.CharField(choices=[('1', '1-2 Apps'), ('2', '2-4 Apps'), ('3', '5+ Apps')], max_length=20)),
                ('response_4', models.CharField(max_length=200, null=True)),
                ('response_5', models.CharField(max_length=200, null=True)),
                ('response_6', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('questions', models.ManyToManyField(null=True, to='questionary.Question')),
            ],
        ),
    ]
