# Generated by Django 3.1.2 on 2021-02-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='response_7',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
