# Generated by Django 3.1.2 on 2021-02-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0002_auto_20210129_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='response',
            field=models.ManyToManyField(to='questionary.Choice'),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
