# Generated by Django 3.1.2 on 2021-02-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0002_userresponse_response_7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(to='questionary.Choice'),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='questions',
            field=models.ManyToManyField(to='questionary.Question'),
        ),
    ]
