# Generated by Django 3.1.2 on 2021-02-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0003_auto_20210201_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='response_date',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='response',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='response',
            field=models.CharField(choices=[('A', 'Yes'), ('B', 'No')], max_length=2, null=True),
        ),
    ]
