# Generated by Django 3.1.2 on 2021-02-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0004_auto_20210201_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresponse',
            old_name='user',
            new_name='username',
        ),
    ]
