# Generated by Django 3.1.2 on 2021-02-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0005_auto_20210201_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresponse',
            old_name='username',
            new_name='user',
        ),
    ]
