# Generated by Django 3.1.2 on 2021-02-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0006_auto_20210201_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='response',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='response_1',
            field=models.CharField(choices=[('1', '250-300'), ('2', '300-500'), ('3', '500-750'), ('4', '1000-1500'), ('5', '1500+')], max_length=20, null=True),
        ),
    ]
