# Generated by Django 3.1.2 on 2021-02-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0008_auto_20210204_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='response_2',
            field=models.CharField(choices=[('1', 'Work'), ('2', 'School'), ('3', 'Leisure/Hobby'), ('4', 'Everything')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='response_3',
            field=models.CharField(choices=[('1', '1-2 Apps'), ('2', '2-4 Apps'), ('3', '5+ Apps')], max_length=20, null=True),
        ),
    ]
