# Generated by Django 3.1.2 on 2021-02-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0009_auto_20210204_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='response_1',
            field=models.CharField(choices=[('1', '250-300'), ('2', '300-500'), ('3', '500-750'), ('4', '1000-1500'), ('5', '1500+')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='response_2',
            field=models.CharField(choices=[('1', 'Work'), ('2', 'School'), ('3', 'Leisure/Hobby'), ('4', 'Everything')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='response_3',
            field=models.CharField(choices=[('1', '1-2 Apps'), ('2', '2-4 Apps'), ('3', '5+ Apps')], max_length=20),
        ),
    ]
