# Generated by Django 3.1.2 on 2021-02-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0010_auto_20210204_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='response_4',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
