# Generated by Django 3.1.7 on 2021-04-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200, unique=True)),
                ('subtitle', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='index/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, max_length=300)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
