# Generated by Django 3.1.2 on 2020-11-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=120)),
                ('publishdate', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=120)),
                ('sub', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='products/%Y/%m/%d/')),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('modelnumber', models.CharField(blank=True, max_length=120)),
                ('size', models.CharField(blank=True, max_length=120)),
                ('weight', models.CharField(blank=True, max_length=120)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
