# Generated by Django 3.1.2 on 2021-01-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='affiliate_link',
        ),
    ]
