# Generated by Django 3.1.2 on 2021-01-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productdetail_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdetail',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
