# Generated by Django 3.1.2 on 2020-10-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productdetail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='products/%Y/%m/%d/'),
        ),
    ]
