# Generated by Django 3.1.7 on 2021-03-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210106_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
