# Generated by Django 3.1.7 on 2021-03-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210310_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='description_overview',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
