# Generated by Django 3.1.2 on 2020-10-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201029_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='products/%Y/%m/%d/'),
        ),
    ]
