# Generated by Django 3.1.7 on 2021-03-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210310_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='processor_corecount',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
