# Generated by Django 3.1.7 on 2021-03-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='image',
        ),
    ]
