# Generated by Django 3.1.7 on 2021-03-19 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210319_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdetail',
            options={'ordering': ['name'], 'verbose_name': 'Product Detail', 'verbose_name_plural': 'Product Details'},
        ),
    ]
